/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginAdminRouteImport } from './routes/login-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPesertaRouteImport } from './routes/_authenticated/peserta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPesertaIndexRouteImport } from './routes/_authenticated/peserta.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiFilesIdRouteImport } from './routes/api.files.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminUjianRouteImport } from './routes/_authenticated/admin.ujian'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin.tools'
import { Route as AuthenticatedAdminPengaturanRouteImport } from './routes/_authenticated/admin.pengaturan'
import { Route as AuthenticatedAdminPanduanRouteImport } from './routes/_authenticated/admin.panduan'
import { Route as AuthenticatedAdminModulRouteImport } from './routes/_authenticated/admin.modul'
import { Route as AuthenticatedAdminFilesRouteImport } from './routes/_authenticated/admin.files'
import { Route as AuthenticatedAdminAkademikRouteImport } from './routes/_authenticated/admin.akademik'
import { Route as AuthenticatedAdminPesertaIndexRouteImport } from './routes/_authenticated/admin.peserta.index'
import { Route as AuthenticatedAdminLeaderboardIndexRouteImport } from './routes/_authenticated/admin.leaderboard.index'
import { Route as AuthenticatedAdminEvaluasiIndexRouteImport } from './routes/_authenticated/admin.evaluasi.index'
import { Route as AuthenticatedAdminAnalitikIndexRouteImport } from './routes/_authenticated/admin.analitik.index'
import { Route as AuthenticatedAdminAkademikIndexRouteImport } from './routes/_authenticated/admin.akademik.index'
import { Route as AuthenticatedAdminUsersRolesRouteImport } from './routes/_authenticated/admin.users.roles'
import { Route as AuthenticatedAdminUjianIdRouteImport } from './routes/_authenticated/admin.ujian.$id'
import { Route as AuthenticatedAdminPesertaOnlineRouteImport } from './routes/_authenticated/admin.peserta.online'
import { Route as AuthenticatedAdminPesertaKartuRouteImport } from './routes/_authenticated/admin.peserta.kartu'
import { Route as AuthenticatedAdminModulImportWordRouteImport } from './routes/_authenticated/admin.modul.import-word'
import { Route as AuthenticatedAdminModulImportRouteImport } from './routes/_authenticated/admin.modul.import'
import { Route as AuthenticatedAdminLeaderboardIdRouteImport } from './routes/_authenticated/admin.leaderboard.$id'
import { Route as AuthenticatedAdminEvaluasiIdRouteImport } from './routes/_authenticated/admin.evaluasi.$id'
import { Route as AuthenticatedAdminAnalitikRekapRouteImport } from './routes/_authenticated/admin.analitik.rekap'
import { Route as AuthenticatedAdminAnalitikAnalisisRouteImport } from './routes/_authenticated/admin.analitik.analisis'
import { Route as AuthenticatedAdminAnalitikIdRouteImport } from './routes/_authenticated/admin.analitik.$id'
import { Route as AuthenticatedAdminAkademikTahunAkademikRouteImport } from './routes/_authenticated/admin.akademik.tahun-akademik'
import { Route as AuthenticatedAdminAkademikSemesterRouteImport } from './routes/_authenticated/admin.akademik.semester'
import { Route as AuthenticatedAdminAkademikMataKuliahRouteImport } from './routes/_authenticated/admin.akademik.mata-kuliah'
import { Route as AuthenticatedPesertaUjianIdIndexRouteImport } from './routes/_authenticated/peserta.ujian.$id.index'
import { Route as AuthenticatedPesertaUjianIdKerjakanRouteImport } from './routes/_authenticated/peserta.ujian.$id.kerjakan'
import { Route as AuthenticatedPesertaUjianIdHasilRouteImport } from './routes/_authenticated/peserta.ujian.$id.hasil'
import { Route as AuthenticatedAdminUjianIdTokenRouteImport } from './routes/_authenticated/admin.ujian.$id.token'
import { Route as AuthenticatedAdminUjianIdPesertaRouteImport } from './routes/_authenticated/admin.ujian.$id.peserta'
import { Route as AuthenticatedAdminTopikIdSoalRouteImport } from './routes/_authenticated/admin.topik.$id.soal'
import { Route as AuthenticatedAdminModulIdTopikRouteImport } from './routes/_authenticated/admin.modul.$id.topik'
import { Route as AuthenticatedAdminEvaluasiUjianIdRouteImport } from './routes/_authenticated/admin.evaluasi.ujian.$id'

const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login-admin',
  path: '/login-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPesertaRoute = AuthenticatedPesertaRouteImport.update({
  id: '/peserta',
  path: '/peserta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPesertaIndexRoute =
  AuthenticatedPesertaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPesertaRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUjianRoute = AuthenticatedAdminUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPengaturanRoute =
  AuthenticatedAdminPengaturanRouteImport.update({
    id: '/pengaturan',
    path: '/pengaturan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPanduanRoute =
  AuthenticatedAdminPanduanRouteImport.update({
    id: '/panduan',
    path: '/panduan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulRoute = AuthenticatedAdminModulRouteImport.update({
  id: '/modul',
  path: '/modul',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFilesRoute = AuthenticatedAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAkademikRoute =
  AuthenticatedAdminAkademikRouteImport.update({
    id: '/akademik',
    path: '/akademik',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPesertaIndexRoute =
  AuthenticatedAdminPesertaIndexRouteImport.update({
    id: '/peserta/',
    path: '/peserta/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeaderboardIndexRoute =
  AuthenticatedAdminLeaderboardIndexRouteImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEvaluasiIndexRoute =
  AuthenticatedAdminEvaluasiIndexRouteImport.update({
    id: '/evaluasi/',
    path: '/evaluasi/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalitikIndexRoute =
  AuthenticatedAdminAnalitikIndexRouteImport.update({
    id: '/analitik/',
    path: '/analitik/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAkademikIndexRoute =
  AuthenticatedAdminAkademikIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAkademikRoute,
  } as any)
const AuthenticatedAdminUsersRolesRoute =
  AuthenticatedAdminUsersRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminUjianIdRoute =
  AuthenticatedAdminUjianIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUjianRoute,
  } as any)
const AuthenticatedAdminPesertaOnlineRoute =
  AuthenticatedAdminPesertaOnlineRouteImport.update({
    id: '/peserta/online',
    path: '/peserta/online',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPesertaKartuRoute =
  AuthenticatedAdminPesertaKartuRouteImport.update({
    id: '/peserta/kartu',
    path: '/peserta/kartu',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulImportWordRoute =
  AuthenticatedAdminModulImportWordRouteImport.update({
    id: '/import-word',
    path: '/import-word',
    getParentRoute: () => AuthenticatedAdminModulRoute,
  } as any)
const AuthenticatedAdminModulImportRoute =
  AuthenticatedAdminModulImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminModulRoute,
  } as any)
const AuthenticatedAdminLeaderboardIdRoute =
  AuthenticatedAdminLeaderboardIdRouteImport.update({
    id: '/leaderboard/$id',
    path: '/leaderboard/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEvaluasiIdRoute =
  AuthenticatedAdminEvaluasiIdRouteImport.update({
    id: '/evaluasi/$id',
    path: '/evaluasi/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalitikRekapRoute =
  AuthenticatedAdminAnalitikRekapRouteImport.update({
    id: '/analitik/rekap',
    path: '/analitik/rekap',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalitikAnalisisRoute =
  AuthenticatedAdminAnalitikAnalisisRouteImport.update({
    id: '/analitik/analisis',
    path: '/analitik/analisis',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalitikIdRoute =
  AuthenticatedAdminAnalitikIdRouteImport.update({
    id: '/analitik/$id',
    path: '/analitik/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAkademikTahunAkademikRoute =
  AuthenticatedAdminAkademikTahunAkademikRouteImport.update({
    id: '/tahun-akademik',
    path: '/tahun-akademik',
    getParentRoute: () => AuthenticatedAdminAkademikRoute,
  } as any)
const AuthenticatedAdminAkademikSemesterRoute =
  AuthenticatedAdminAkademikSemesterRouteImport.update({
    id: '/semester',
    path: '/semester',
    getParentRoute: () => AuthenticatedAdminAkademikRoute,
  } as any)
const AuthenticatedAdminAkademikMataKuliahRoute =
  AuthenticatedAdminAkademikMataKuliahRouteImport.update({
    id: '/mata-kuliah',
    path: '/mata-kuliah',
    getParentRoute: () => AuthenticatedAdminAkademikRoute,
  } as any)
const AuthenticatedPesertaUjianIdIndexRoute =
  AuthenticatedPesertaUjianIdIndexRouteImport.update({
    id: '/ujian/$id/',
    path: '/ujian/$id/',
    getParentRoute: () => AuthenticatedPesertaRoute,
  } as any)
const AuthenticatedPesertaUjianIdKerjakanRoute =
  AuthenticatedPesertaUjianIdKerjakanRouteImport.update({
    id: '/ujian/$id/kerjakan',
    path: '/ujian/$id/kerjakan',
    getParentRoute: () => AuthenticatedPesertaRoute,
  } as any)
const AuthenticatedPesertaUjianIdHasilRoute =
  AuthenticatedPesertaUjianIdHasilRouteImport.update({
    id: '/ujian/$id/hasil',
    path: '/ujian/$id/hasil',
    getParentRoute: () => AuthenticatedPesertaRoute,
  } as any)
const AuthenticatedAdminUjianIdTokenRoute =
  AuthenticatedAdminUjianIdTokenRouteImport.update({
    id: '/token',
    path: '/token',
    getParentRoute: () => AuthenticatedAdminUjianIdRoute,
  } as any)
const AuthenticatedAdminUjianIdPesertaRoute =
  AuthenticatedAdminUjianIdPesertaRouteImport.update({
    id: '/peserta',
    path: '/peserta',
    getParentRoute: () => AuthenticatedAdminUjianIdRoute,
  } as any)
const AuthenticatedAdminTopikIdSoalRoute =
  AuthenticatedAdminTopikIdSoalRouteImport.update({
    id: '/topik/$id/soal',
    path: '/topik/$id/soal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulIdTopikRoute =
  AuthenticatedAdminModulIdTopikRouteImport.update({
    id: '/$id/topik',
    path: '/$id/topik',
    getParentRoute: () => AuthenticatedAdminModulRoute,
  } as any)
const AuthenticatedAdminEvaluasiUjianIdRoute =
  AuthenticatedAdminEvaluasiUjianIdRouteImport.update({
    id: '/evaluasi/ujian/$id',
    path: '/evaluasi/ujian/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-admin': typeof LoginAdminRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/peserta': typeof AuthenticatedPesertaRouteWithChildren
  '/admin/akademik': typeof AuthenticatedAdminAkademikRouteWithChildren
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/modul': typeof AuthenticatedAdminModulRouteWithChildren
  '/admin/panduan': typeof AuthenticatedAdminPanduanRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/ujian': typeof AuthenticatedAdminUjianRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/api/files/$id': typeof ApiFilesIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/peserta/': typeof AuthenticatedPesertaIndexRoute
  '/admin/akademik/mata-kuliah': typeof AuthenticatedAdminAkademikMataKuliahRoute
  '/admin/akademik/semester': typeof AuthenticatedAdminAkademikSemesterRoute
  '/admin/akademik/tahun-akademik': typeof AuthenticatedAdminAkademikTahunAkademikRoute
  '/admin/analitik/$id': typeof AuthenticatedAdminAnalitikIdRoute
  '/admin/analitik/analisis': typeof AuthenticatedAdminAnalitikAnalisisRoute
  '/admin/analitik/rekap': typeof AuthenticatedAdminAnalitikRekapRoute
  '/admin/evaluasi/$id': typeof AuthenticatedAdminEvaluasiIdRoute
  '/admin/leaderboard/$id': typeof AuthenticatedAdminLeaderboardIdRoute
  '/admin/modul/import': typeof AuthenticatedAdminModulImportRoute
  '/admin/modul/import-word': typeof AuthenticatedAdminModulImportWordRoute
  '/admin/peserta/kartu': typeof AuthenticatedAdminPesertaKartuRoute
  '/admin/peserta/online': typeof AuthenticatedAdminPesertaOnlineRoute
  '/admin/ujian/$id': typeof AuthenticatedAdminUjianIdRouteWithChildren
  '/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/admin/akademik/': typeof AuthenticatedAdminAkademikIndexRoute
  '/admin/analitik/': typeof AuthenticatedAdminAnalitikIndexRoute
  '/admin/evaluasi/': typeof AuthenticatedAdminEvaluasiIndexRoute
  '/admin/leaderboard/': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/admin/peserta/': typeof AuthenticatedAdminPesertaIndexRoute
  '/admin/evaluasi/ujian/$id': typeof AuthenticatedAdminEvaluasiUjianIdRoute
  '/admin/modul/$id/topik': typeof AuthenticatedAdminModulIdTopikRoute
  '/admin/topik/$id/soal': typeof AuthenticatedAdminTopikIdSoalRoute
  '/admin/ujian/$id/peserta': typeof AuthenticatedAdminUjianIdPesertaRoute
  '/admin/ujian/$id/token': typeof AuthenticatedAdminUjianIdTokenRoute
  '/peserta/ujian/$id/hasil': typeof AuthenticatedPesertaUjianIdHasilRoute
  '/peserta/ujian/$id/kerjakan': typeof AuthenticatedPesertaUjianIdKerjakanRoute
  '/peserta/ujian/$id/': typeof AuthenticatedPesertaUjianIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-admin': typeof LoginAdminRoute
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/modul': typeof AuthenticatedAdminModulRouteWithChildren
  '/admin/panduan': typeof AuthenticatedAdminPanduanRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/ujian': typeof AuthenticatedAdminUjianRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/api/files/$id': typeof ApiFilesIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/peserta': typeof AuthenticatedPesertaIndexRoute
  '/admin/akademik/mata-kuliah': typeof AuthenticatedAdminAkademikMataKuliahRoute
  '/admin/akademik/semester': typeof AuthenticatedAdminAkademikSemesterRoute
  '/admin/akademik/tahun-akademik': typeof AuthenticatedAdminAkademikTahunAkademikRoute
  '/admin/analitik/$id': typeof AuthenticatedAdminAnalitikIdRoute
  '/admin/analitik/analisis': typeof AuthenticatedAdminAnalitikAnalisisRoute
  '/admin/analitik/rekap': typeof AuthenticatedAdminAnalitikRekapRoute
  '/admin/evaluasi/$id': typeof AuthenticatedAdminEvaluasiIdRoute
  '/admin/leaderboard/$id': typeof AuthenticatedAdminLeaderboardIdRoute
  '/admin/modul/import': typeof AuthenticatedAdminModulImportRoute
  '/admin/modul/import-word': typeof AuthenticatedAdminModulImportWordRoute
  '/admin/peserta/kartu': typeof AuthenticatedAdminPesertaKartuRoute
  '/admin/peserta/online': typeof AuthenticatedAdminPesertaOnlineRoute
  '/admin/ujian/$id': typeof AuthenticatedAdminUjianIdRouteWithChildren
  '/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/admin/akademik': typeof AuthenticatedAdminAkademikIndexRoute
  '/admin/analitik': typeof AuthenticatedAdminAnalitikIndexRoute
  '/admin/evaluasi': typeof AuthenticatedAdminEvaluasiIndexRoute
  '/admin/leaderboard': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/admin/peserta': typeof AuthenticatedAdminPesertaIndexRoute
  '/admin/evaluasi/ujian/$id': typeof AuthenticatedAdminEvaluasiUjianIdRoute
  '/admin/modul/$id/topik': typeof AuthenticatedAdminModulIdTopikRoute
  '/admin/topik/$id/soal': typeof AuthenticatedAdminTopikIdSoalRoute
  '/admin/ujian/$id/peserta': typeof AuthenticatedAdminUjianIdPesertaRoute
  '/admin/ujian/$id/token': typeof AuthenticatedAdminUjianIdTokenRoute
  '/peserta/ujian/$id/hasil': typeof AuthenticatedPesertaUjianIdHasilRoute
  '/peserta/ujian/$id/kerjakan': typeof AuthenticatedPesertaUjianIdKerjakanRoute
  '/peserta/ujian/$id': typeof AuthenticatedPesertaUjianIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/login-admin': typeof LoginAdminRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/peserta': typeof AuthenticatedPesertaRouteWithChildren
  '/_authenticated/admin/akademik': typeof AuthenticatedAdminAkademikRouteWithChildren
  '/_authenticated/admin/files': typeof AuthenticatedAdminFilesRoute
  '/_authenticated/admin/modul': typeof AuthenticatedAdminModulRouteWithChildren
  '/_authenticated/admin/panduan': typeof AuthenticatedAdminPanduanRoute
  '/_authenticated/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/admin/ujian': typeof AuthenticatedAdminUjianRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/api/files/$id': typeof ApiFilesIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/peserta/': typeof AuthenticatedPesertaIndexRoute
  '/_authenticated/admin/akademik/mata-kuliah': typeof AuthenticatedAdminAkademikMataKuliahRoute
  '/_authenticated/admin/akademik/semester': typeof AuthenticatedAdminAkademikSemesterRoute
  '/_authenticated/admin/akademik/tahun-akademik': typeof AuthenticatedAdminAkademikTahunAkademikRoute
  '/_authenticated/admin/analitik/$id': typeof AuthenticatedAdminAnalitikIdRoute
  '/_authenticated/admin/analitik/analisis': typeof AuthenticatedAdminAnalitikAnalisisRoute
  '/_authenticated/admin/analitik/rekap': typeof AuthenticatedAdminAnalitikRekapRoute
  '/_authenticated/admin/evaluasi/$id': typeof AuthenticatedAdminEvaluasiIdRoute
  '/_authenticated/admin/leaderboard/$id': typeof AuthenticatedAdminLeaderboardIdRoute
  '/_authenticated/admin/modul/import': typeof AuthenticatedAdminModulImportRoute
  '/_authenticated/admin/modul/import-word': typeof AuthenticatedAdminModulImportWordRoute
  '/_authenticated/admin/peserta/kartu': typeof AuthenticatedAdminPesertaKartuRoute
  '/_authenticated/admin/peserta/online': typeof AuthenticatedAdminPesertaOnlineRoute
  '/_authenticated/admin/ujian/$id': typeof AuthenticatedAdminUjianIdRouteWithChildren
  '/_authenticated/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/_authenticated/admin/akademik/': typeof AuthenticatedAdminAkademikIndexRoute
  '/_authenticated/admin/analitik/': typeof AuthenticatedAdminAnalitikIndexRoute
  '/_authenticated/admin/evaluasi/': typeof AuthenticatedAdminEvaluasiIndexRoute
  '/_authenticated/admin/leaderboard/': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/_authenticated/admin/peserta/': typeof AuthenticatedAdminPesertaIndexRoute
  '/_authenticated/admin/evaluasi/ujian/$id': typeof AuthenticatedAdminEvaluasiUjianIdRoute
  '/_authenticated/admin/modul/$id/topik': typeof AuthenticatedAdminModulIdTopikRoute
  '/_authenticated/admin/topik/$id/soal': typeof AuthenticatedAdminTopikIdSoalRoute
  '/_authenticated/admin/ujian/$id/peserta': typeof AuthenticatedAdminUjianIdPesertaRoute
  '/_authenticated/admin/ujian/$id/token': typeof AuthenticatedAdminUjianIdTokenRoute
  '/_authenticated/peserta/ujian/$id/hasil': typeof AuthenticatedPesertaUjianIdHasilRoute
  '/_authenticated/peserta/ujian/$id/kerjakan': typeof AuthenticatedPesertaUjianIdKerjakanRoute
  '/_authenticated/peserta/ujian/$id/': typeof AuthenticatedPesertaUjianIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login-admin'
    | '/admin'
    | '/peserta'
    | '/admin/akademik'
    | '/admin/files'
    | '/admin/modul'
    | '/admin/panduan'
    | '/admin/pengaturan'
    | '/admin/tools'
    | '/admin/ujian'
    | '/admin/users'
    | '/api/files/$id'
    | '/admin/'
    | '/peserta/'
    | '/admin/akademik/mata-kuliah'
    | '/admin/akademik/semester'
    | '/admin/akademik/tahun-akademik'
    | '/admin/analitik/$id'
    | '/admin/analitik/analisis'
    | '/admin/analitik/rekap'
    | '/admin/evaluasi/$id'
    | '/admin/leaderboard/$id'
    | '/admin/modul/import'
    | '/admin/modul/import-word'
    | '/admin/peserta/kartu'
    | '/admin/peserta/online'
    | '/admin/ujian/$id'
    | '/admin/users/roles'
    | '/admin/akademik/'
    | '/admin/analitik/'
    | '/admin/evaluasi/'
    | '/admin/leaderboard/'
    | '/admin/peserta/'
    | '/admin/evaluasi/ujian/$id'
    | '/admin/modul/$id/topik'
    | '/admin/topik/$id/soal'
    | '/admin/ujian/$id/peserta'
    | '/admin/ujian/$id/token'
    | '/peserta/ujian/$id/hasil'
    | '/peserta/ujian/$id/kerjakan'
    | '/peserta/ujian/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login-admin'
    | '/admin/files'
    | '/admin/modul'
    | '/admin/panduan'
    | '/admin/pengaturan'
    | '/admin/tools'
    | '/admin/ujian'
    | '/admin/users'
    | '/api/files/$id'
    | '/admin'
    | '/peserta'
    | '/admin/akademik/mata-kuliah'
    | '/admin/akademik/semester'
    | '/admin/akademik/tahun-akademik'
    | '/admin/analitik/$id'
    | '/admin/analitik/analisis'
    | '/admin/analitik/rekap'
    | '/admin/evaluasi/$id'
    | '/admin/leaderboard/$id'
    | '/admin/modul/import'
    | '/admin/modul/import-word'
    | '/admin/peserta/kartu'
    | '/admin/peserta/online'
    | '/admin/ujian/$id'
    | '/admin/users/roles'
    | '/admin/akademik'
    | '/admin/analitik'
    | '/admin/evaluasi'
    | '/admin/leaderboard'
    | '/admin/peserta'
    | '/admin/evaluasi/ujian/$id'
    | '/admin/modul/$id/topik'
    | '/admin/topik/$id/soal'
    | '/admin/ujian/$id/peserta'
    | '/admin/ujian/$id/token'
    | '/peserta/ujian/$id/hasil'
    | '/peserta/ujian/$id/kerjakan'
    | '/peserta/ujian/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/login-admin'
    | '/_authenticated/admin'
    | '/_authenticated/peserta'
    | '/_authenticated/admin/akademik'
    | '/_authenticated/admin/files'
    | '/_authenticated/admin/modul'
    | '/_authenticated/admin/panduan'
    | '/_authenticated/admin/pengaturan'
    | '/_authenticated/admin/tools'
    | '/_authenticated/admin/ujian'
    | '/_authenticated/admin/users'
    | '/api/files/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/peserta/'
    | '/_authenticated/admin/akademik/mata-kuliah'
    | '/_authenticated/admin/akademik/semester'
    | '/_authenticated/admin/akademik/tahun-akademik'
    | '/_authenticated/admin/analitik/$id'
    | '/_authenticated/admin/analitik/analisis'
    | '/_authenticated/admin/analitik/rekap'
    | '/_authenticated/admin/evaluasi/$id'
    | '/_authenticated/admin/leaderboard/$id'
    | '/_authenticated/admin/modul/import'
    | '/_authenticated/admin/modul/import-word'
    | '/_authenticated/admin/peserta/kartu'
    | '/_authenticated/admin/peserta/online'
    | '/_authenticated/admin/ujian/$id'
    | '/_authenticated/admin/users/roles'
    | '/_authenticated/admin/akademik/'
    | '/_authenticated/admin/analitik/'
    | '/_authenticated/admin/evaluasi/'
    | '/_authenticated/admin/leaderboard/'
    | '/_authenticated/admin/peserta/'
    | '/_authenticated/admin/evaluasi/ujian/$id'
    | '/_authenticated/admin/modul/$id/topik'
    | '/_authenticated/admin/topik/$id/soal'
    | '/_authenticated/admin/ujian/$id/peserta'
    | '/_authenticated/admin/ujian/$id/token'
    | '/_authenticated/peserta/ujian/$id/hasil'
    | '/_authenticated/peserta/ujian/$id/kerjakan'
    | '/_authenticated/peserta/ujian/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginAdminRoute: typeof LoginAdminRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-admin': {
      id: '/login-admin'
      path: '/login-admin'
      fullPath: '/login-admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/peserta': {
      id: '/_authenticated/peserta'
      path: '/peserta'
      fullPath: '/peserta'
      preLoaderRoute: typeof AuthenticatedPesertaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/peserta/': {
      id: '/_authenticated/peserta/'
      path: '/'
      fullPath: '/peserta/'
      preLoaderRoute: typeof AuthenticatedPesertaIndexRouteImport
      parentRoute: typeof AuthenticatedPesertaRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ujian': {
      id: '/_authenticated/admin/ujian'
      path: '/ujian'
      fullPath: '/admin/ujian'
      preLoaderRoute: typeof AuthenticatedAdminUjianRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pengaturan': {
      id: '/_authenticated/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AuthenticatedAdminPengaturanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/panduan': {
      id: '/_authenticated/admin/panduan'
      path: '/panduan'
      fullPath: '/admin/panduan'
      preLoaderRoute: typeof AuthenticatedAdminPanduanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modul': {
      id: '/_authenticated/admin/modul'
      path: '/modul'
      fullPath: '/admin/modul'
      preLoaderRoute: typeof AuthenticatedAdminModulRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/files': {
      id: '/_authenticated/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AuthenticatedAdminFilesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/akademik': {
      id: '/_authenticated/admin/akademik'
      path: '/akademik'
      fullPath: '/admin/akademik'
      preLoaderRoute: typeof AuthenticatedAdminAkademikRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/peserta/': {
      id: '/_authenticated/admin/peserta/'
      path: '/peserta'
      fullPath: '/admin/peserta/'
      preLoaderRoute: typeof AuthenticatedAdminPesertaIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leaderboard/': {
      id: '/_authenticated/admin/leaderboard/'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard/'
      preLoaderRoute: typeof AuthenticatedAdminLeaderboardIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/evaluasi/': {
      id: '/_authenticated/admin/evaluasi/'
      path: '/evaluasi'
      fullPath: '/admin/evaluasi/'
      preLoaderRoute: typeof AuthenticatedAdminEvaluasiIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analitik/': {
      id: '/_authenticated/admin/analitik/'
      path: '/analitik'
      fullPath: '/admin/analitik/'
      preLoaderRoute: typeof AuthenticatedAdminAnalitikIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/akademik/': {
      id: '/_authenticated/admin/akademik/'
      path: '/'
      fullPath: '/admin/akademik/'
      preLoaderRoute: typeof AuthenticatedAdminAkademikIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAkademikRoute
    }
    '/_authenticated/admin/users/roles': {
      id: '/_authenticated/admin/users/roles'
      path: '/roles'
      fullPath: '/admin/users/roles'
      preLoaderRoute: typeof AuthenticatedAdminUsersRolesRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/ujian/$id': {
      id: '/_authenticated/admin/ujian/$id'
      path: '/$id'
      fullPath: '/admin/ujian/$id'
      preLoaderRoute: typeof AuthenticatedAdminUjianIdRouteImport
      parentRoute: typeof AuthenticatedAdminUjianRoute
    }
    '/_authenticated/admin/peserta/online': {
      id: '/_authenticated/admin/peserta/online'
      path: '/peserta/online'
      fullPath: '/admin/peserta/online'
      preLoaderRoute: typeof AuthenticatedAdminPesertaOnlineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/peserta/kartu': {
      id: '/_authenticated/admin/peserta/kartu'
      path: '/peserta/kartu'
      fullPath: '/admin/peserta/kartu'
      preLoaderRoute: typeof AuthenticatedAdminPesertaKartuRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modul/import-word': {
      id: '/_authenticated/admin/modul/import-word'
      path: '/import-word'
      fullPath: '/admin/modul/import-word'
      preLoaderRoute: typeof AuthenticatedAdminModulImportWordRouteImport
      parentRoute: typeof AuthenticatedAdminModulRoute
    }
    '/_authenticated/admin/modul/import': {
      id: '/_authenticated/admin/modul/import'
      path: '/import'
      fullPath: '/admin/modul/import'
      preLoaderRoute: typeof AuthenticatedAdminModulImportRouteImport
      parentRoute: typeof AuthenticatedAdminModulRoute
    }
    '/_authenticated/admin/leaderboard/$id': {
      id: '/_authenticated/admin/leaderboard/$id'
      path: '/leaderboard/$id'
      fullPath: '/admin/leaderboard/$id'
      preLoaderRoute: typeof AuthenticatedAdminLeaderboardIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/evaluasi/$id': {
      id: '/_authenticated/admin/evaluasi/$id'
      path: '/evaluasi/$id'
      fullPath: '/admin/evaluasi/$id'
      preLoaderRoute: typeof AuthenticatedAdminEvaluasiIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analitik/rekap': {
      id: '/_authenticated/admin/analitik/rekap'
      path: '/analitik/rekap'
      fullPath: '/admin/analitik/rekap'
      preLoaderRoute: typeof AuthenticatedAdminAnalitikRekapRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analitik/analisis': {
      id: '/_authenticated/admin/analitik/analisis'
      path: '/analitik/analisis'
      fullPath: '/admin/analitik/analisis'
      preLoaderRoute: typeof AuthenticatedAdminAnalitikAnalisisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analitik/$id': {
      id: '/_authenticated/admin/analitik/$id'
      path: '/analitik/$id'
      fullPath: '/admin/analitik/$id'
      preLoaderRoute: typeof AuthenticatedAdminAnalitikIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/akademik/tahun-akademik': {
      id: '/_authenticated/admin/akademik/tahun-akademik'
      path: '/tahun-akademik'
      fullPath: '/admin/akademik/tahun-akademik'
      preLoaderRoute: typeof AuthenticatedAdminAkademikTahunAkademikRouteImport
      parentRoute: typeof AuthenticatedAdminAkademikRoute
    }
    '/_authenticated/admin/akademik/semester': {
      id: '/_authenticated/admin/akademik/semester'
      path: '/semester'
      fullPath: '/admin/akademik/semester'
      preLoaderRoute: typeof AuthenticatedAdminAkademikSemesterRouteImport
      parentRoute: typeof AuthenticatedAdminAkademikRoute
    }
    '/_authenticated/admin/akademik/mata-kuliah': {
      id: '/_authenticated/admin/akademik/mata-kuliah'
      path: '/mata-kuliah'
      fullPath: '/admin/akademik/mata-kuliah'
      preLoaderRoute: typeof AuthenticatedAdminAkademikMataKuliahRouteImport
      parentRoute: typeof AuthenticatedAdminAkademikRoute
    }
    '/_authenticated/peserta/ujian/$id/': {
      id: '/_authenticated/peserta/ujian/$id/'
      path: '/ujian/$id'
      fullPath: '/peserta/ujian/$id/'
      preLoaderRoute: typeof AuthenticatedPesertaUjianIdIndexRouteImport
      parentRoute: typeof AuthenticatedPesertaRoute
    }
    '/_authenticated/peserta/ujian/$id/kerjakan': {
      id: '/_authenticated/peserta/ujian/$id/kerjakan'
      path: '/ujian/$id/kerjakan'
      fullPath: '/peserta/ujian/$id/kerjakan'
      preLoaderRoute: typeof AuthenticatedPesertaUjianIdKerjakanRouteImport
      parentRoute: typeof AuthenticatedPesertaRoute
    }
    '/_authenticated/peserta/ujian/$id/hasil': {
      id: '/_authenticated/peserta/ujian/$id/hasil'
      path: '/ujian/$id/hasil'
      fullPath: '/peserta/ujian/$id/hasil'
      preLoaderRoute: typeof AuthenticatedPesertaUjianIdHasilRouteImport
      parentRoute: typeof AuthenticatedPesertaRoute
    }
    '/_authenticated/admin/ujian/$id/token': {
      id: '/_authenticated/admin/ujian/$id/token'
      path: '/token'
      fullPath: '/admin/ujian/$id/token'
      preLoaderRoute: typeof AuthenticatedAdminUjianIdTokenRouteImport
      parentRoute: typeof AuthenticatedAdminUjianIdRoute
    }
    '/_authenticated/admin/ujian/$id/peserta': {
      id: '/_authenticated/admin/ujian/$id/peserta'
      path: '/peserta'
      fullPath: '/admin/ujian/$id/peserta'
      preLoaderRoute: typeof AuthenticatedAdminUjianIdPesertaRouteImport
      parentRoute: typeof AuthenticatedAdminUjianIdRoute
    }
    '/_authenticated/admin/topik/$id/soal': {
      id: '/_authenticated/admin/topik/$id/soal'
      path: '/topik/$id/soal'
      fullPath: '/admin/topik/$id/soal'
      preLoaderRoute: typeof AuthenticatedAdminTopikIdSoalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modul/$id/topik': {
      id: '/_authenticated/admin/modul/$id/topik'
      path: '/$id/topik'
      fullPath: '/admin/modul/$id/topik'
      preLoaderRoute: typeof AuthenticatedAdminModulIdTopikRouteImport
      parentRoute: typeof AuthenticatedAdminModulRoute
    }
    '/_authenticated/admin/evaluasi/ujian/$id': {
      id: '/_authenticated/admin/evaluasi/ujian/$id'
      path: '/evaluasi/ujian/$id'
      fullPath: '/admin/evaluasi/ujian/$id'
      preLoaderRoute: typeof AuthenticatedAdminEvaluasiUjianIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminAkademikRouteChildren {
  AuthenticatedAdminAkademikMataKuliahRoute: typeof AuthenticatedAdminAkademikMataKuliahRoute
  AuthenticatedAdminAkademikSemesterRoute: typeof AuthenticatedAdminAkademikSemesterRoute
  AuthenticatedAdminAkademikTahunAkademikRoute: typeof AuthenticatedAdminAkademikTahunAkademikRoute
  AuthenticatedAdminAkademikIndexRoute: typeof AuthenticatedAdminAkademikIndexRoute
}

const AuthenticatedAdminAkademikRouteChildren: AuthenticatedAdminAkademikRouteChildren =
  {
    AuthenticatedAdminAkademikMataKuliahRoute:
      AuthenticatedAdminAkademikMataKuliahRoute,
    AuthenticatedAdminAkademikSemesterRoute:
      AuthenticatedAdminAkademikSemesterRoute,
    AuthenticatedAdminAkademikTahunAkademikRoute:
      AuthenticatedAdminAkademikTahunAkademikRoute,
    AuthenticatedAdminAkademikIndexRoute: AuthenticatedAdminAkademikIndexRoute,
  }

const AuthenticatedAdminAkademikRouteWithChildren =
  AuthenticatedAdminAkademikRoute._addFileChildren(
    AuthenticatedAdminAkademikRouteChildren,
  )

interface AuthenticatedAdminModulRouteChildren {
  AuthenticatedAdminModulImportRoute: typeof AuthenticatedAdminModulImportRoute
  AuthenticatedAdminModulImportWordRoute: typeof AuthenticatedAdminModulImportWordRoute
  AuthenticatedAdminModulIdTopikRoute: typeof AuthenticatedAdminModulIdTopikRoute
}

const AuthenticatedAdminModulRouteChildren: AuthenticatedAdminModulRouteChildren =
  {
    AuthenticatedAdminModulImportRoute: AuthenticatedAdminModulImportRoute,
    AuthenticatedAdminModulImportWordRoute:
      AuthenticatedAdminModulImportWordRoute,
    AuthenticatedAdminModulIdTopikRoute: AuthenticatedAdminModulIdTopikRoute,
  }

const AuthenticatedAdminModulRouteWithChildren =
  AuthenticatedAdminModulRoute._addFileChildren(
    AuthenticatedAdminModulRouteChildren,
  )

interface AuthenticatedAdminUjianIdRouteChildren {
  AuthenticatedAdminUjianIdPesertaRoute: typeof AuthenticatedAdminUjianIdPesertaRoute
  AuthenticatedAdminUjianIdTokenRoute: typeof AuthenticatedAdminUjianIdTokenRoute
}

const AuthenticatedAdminUjianIdRouteChildren: AuthenticatedAdminUjianIdRouteChildren =
  {
    AuthenticatedAdminUjianIdPesertaRoute:
      AuthenticatedAdminUjianIdPesertaRoute,
    AuthenticatedAdminUjianIdTokenRoute: AuthenticatedAdminUjianIdTokenRoute,
  }

const AuthenticatedAdminUjianIdRouteWithChildren =
  AuthenticatedAdminUjianIdRoute._addFileChildren(
    AuthenticatedAdminUjianIdRouteChildren,
  )

interface AuthenticatedAdminUjianRouteChildren {
  AuthenticatedAdminUjianIdRoute: typeof AuthenticatedAdminUjianIdRouteWithChildren
}

const AuthenticatedAdminUjianRouteChildren: AuthenticatedAdminUjianRouteChildren =
  {
    AuthenticatedAdminUjianIdRoute: AuthenticatedAdminUjianIdRouteWithChildren,
  }

const AuthenticatedAdminUjianRouteWithChildren =
  AuthenticatedAdminUjianRoute._addFileChildren(
    AuthenticatedAdminUjianRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersRolesRoute: typeof AuthenticatedAdminUsersRolesRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersRolesRoute: AuthenticatedAdminUsersRolesRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAkademikRoute: typeof AuthenticatedAdminAkademikRouteWithChildren
  AuthenticatedAdminFilesRoute: typeof AuthenticatedAdminFilesRoute
  AuthenticatedAdminModulRoute: typeof AuthenticatedAdminModulRouteWithChildren
  AuthenticatedAdminPanduanRoute: typeof AuthenticatedAdminPanduanRoute
  AuthenticatedAdminPengaturanRoute: typeof AuthenticatedAdminPengaturanRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedAdminUjianRoute: typeof AuthenticatedAdminUjianRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAnalitikIdRoute: typeof AuthenticatedAdminAnalitikIdRoute
  AuthenticatedAdminAnalitikAnalisisRoute: typeof AuthenticatedAdminAnalitikAnalisisRoute
  AuthenticatedAdminAnalitikRekapRoute: typeof AuthenticatedAdminAnalitikRekapRoute
  AuthenticatedAdminEvaluasiIdRoute: typeof AuthenticatedAdminEvaluasiIdRoute
  AuthenticatedAdminLeaderboardIdRoute: typeof AuthenticatedAdminLeaderboardIdRoute
  AuthenticatedAdminPesertaKartuRoute: typeof AuthenticatedAdminPesertaKartuRoute
  AuthenticatedAdminPesertaOnlineRoute: typeof AuthenticatedAdminPesertaOnlineRoute
  AuthenticatedAdminAnalitikIndexRoute: typeof AuthenticatedAdminAnalitikIndexRoute
  AuthenticatedAdminEvaluasiIndexRoute: typeof AuthenticatedAdminEvaluasiIndexRoute
  AuthenticatedAdminLeaderboardIndexRoute: typeof AuthenticatedAdminLeaderboardIndexRoute
  AuthenticatedAdminPesertaIndexRoute: typeof AuthenticatedAdminPesertaIndexRoute
  AuthenticatedAdminEvaluasiUjianIdRoute: typeof AuthenticatedAdminEvaluasiUjianIdRoute
  AuthenticatedAdminTopikIdSoalRoute: typeof AuthenticatedAdminTopikIdSoalRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAkademikRoute: AuthenticatedAdminAkademikRouteWithChildren,
  AuthenticatedAdminFilesRoute: AuthenticatedAdminFilesRoute,
  AuthenticatedAdminModulRoute: AuthenticatedAdminModulRouteWithChildren,
  AuthenticatedAdminPanduanRoute: AuthenticatedAdminPanduanRoute,
  AuthenticatedAdminPengaturanRoute: AuthenticatedAdminPengaturanRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedAdminUjianRoute: AuthenticatedAdminUjianRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAnalitikIdRoute: AuthenticatedAdminAnalitikIdRoute,
  AuthenticatedAdminAnalitikAnalisisRoute:
    AuthenticatedAdminAnalitikAnalisisRoute,
  AuthenticatedAdminAnalitikRekapRoute: AuthenticatedAdminAnalitikRekapRoute,
  AuthenticatedAdminEvaluasiIdRoute: AuthenticatedAdminEvaluasiIdRoute,
  AuthenticatedAdminLeaderboardIdRoute: AuthenticatedAdminLeaderboardIdRoute,
  AuthenticatedAdminPesertaKartuRoute: AuthenticatedAdminPesertaKartuRoute,
  AuthenticatedAdminPesertaOnlineRoute: AuthenticatedAdminPesertaOnlineRoute,
  AuthenticatedAdminAnalitikIndexRoute: AuthenticatedAdminAnalitikIndexRoute,
  AuthenticatedAdminEvaluasiIndexRoute: AuthenticatedAdminEvaluasiIndexRoute,
  AuthenticatedAdminLeaderboardIndexRoute:
    AuthenticatedAdminLeaderboardIndexRoute,
  AuthenticatedAdminPesertaIndexRoute: AuthenticatedAdminPesertaIndexRoute,
  AuthenticatedAdminEvaluasiUjianIdRoute:
    AuthenticatedAdminEvaluasiUjianIdRoute,
  AuthenticatedAdminTopikIdSoalRoute: AuthenticatedAdminTopikIdSoalRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPesertaRouteChildren {
  AuthenticatedPesertaIndexRoute: typeof AuthenticatedPesertaIndexRoute
  AuthenticatedPesertaUjianIdHasilRoute: typeof AuthenticatedPesertaUjianIdHasilRoute
  AuthenticatedPesertaUjianIdKerjakanRoute: typeof AuthenticatedPesertaUjianIdKerjakanRoute
  AuthenticatedPesertaUjianIdIndexRoute: typeof AuthenticatedPesertaUjianIdIndexRoute
}

const AuthenticatedPesertaRouteChildren: AuthenticatedPesertaRouteChildren = {
  AuthenticatedPesertaIndexRoute: AuthenticatedPesertaIndexRoute,
  AuthenticatedPesertaUjianIdHasilRoute: AuthenticatedPesertaUjianIdHasilRoute,
  AuthenticatedPesertaUjianIdKerjakanRoute:
    AuthenticatedPesertaUjianIdKerjakanRoute,
  AuthenticatedPesertaUjianIdIndexRoute: AuthenticatedPesertaUjianIdIndexRoute,
}

const AuthenticatedPesertaRouteWithChildren =
  AuthenticatedPesertaRoute._addFileChildren(AuthenticatedPesertaRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPesertaRoute: typeof AuthenticatedPesertaRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPesertaRoute: AuthenticatedPesertaRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginAdminRoute: LoginAdminRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
